apiVersion: apps/v1
kind: Deployment
metadata:
  name: fc-deployment
  labels:
    app: fc
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fc
  template:
    metadata:
      labels:
        app: fc
    spec:
      containers:
      - name: fc
        image: jnsjnsn/fc-front:v4
        ports:
        - containerPort: 80
